### ISSUE TITLE
Integrate with fakegato-history

### ISSUE THREAD

**Issue by lauritarhonen** [pakastin/homebridge-ruuvitag#1]
Would be cool if you could integrate also the [fakegato-history
](https://github.com/simont77/fakegato-history) service in order to be able to show a historical graph for temperatures in the Elgato Eve home app.

Looking at an implementation [here](https://github.com/NorthernMan54/homebridge-dht/blob/master/index.js), it doe not seem to require many lines of code to be added.

**Comment by pakastin** [comment]
I'd like to keep this plugin 100 % Apple Home compliant, since I've found it's easy to broke the setup needing a reinstall with a new PIN code etc.. So it would make more sense to create a separate plugin. You can compose homebridge plugins after all.
