### ISSUE TITLE
Values zero after raspberry update

### ISSUE THREAD

**Issue by tomppakoo** [pakastin/homebridge-ruuvitag#2]
Hello. Ive been running this plugin on raspberry homebridge successfully for months. After last os upgrade values for temperature and humidity displays only zeroes for all ruuvitags.
Ruuvitag-debug displays info correctly as well as hcitool lescan can read ruuvitags fine. I cannot find any clue from homebridge logs. Any hints instead of restoring old version from backup would be appreciated.

**Comment by pakastin** [comment]
Hi! I’ll try to update dependencies if that would do the trick! 😉

**Comment by pakastin** [comment]
Let me know if updating dependencies helped out..?

**Comment by tomppakoo** [comment]
Solved! Not an ruuvitag plugin or dependency problem at all.
OS update/upgrade removed node.js binary cap_net_raw permissions which were fixed using "sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)"
Hope this info helps if someone struggles with the same issue after upgrade. Thank you.

**Comment by pakastin** [comment]
Wow, ok glad you figured that out! 👌
