### ISSUE TITLE
Wrong values 

### ISSUE THREAD

**Issue by DanielHauer** [pakastin/homebridge-ruuvitag#3]
First: The Ruuvi iOS app can see all my Ruuvi tags and displays the correct values.

I then have installed the homebridge plugin and everything worked fine. Homebridge is running and I can see the temperature and humidity. But unfortunately the values are completely wrong (e.g. humidity 10% and temperature -110 degree Celsius). I also recognized that the dataFormat is "5" on my iOS App but "3" in the output of "ruuvitag-debug". Do I have to change that somewhere or is this also just a misinterpretation?

I'm using a Raspi Zero with Raspbian and the straightforward hombebridge installation.

**Comment by pakastin** [comment]
Do you have your Ruuvis in raw or the default mode?

**Comment by DanielHauer** [comment]
Oh, that fixed the problem.
It seems like the plugin only works with the raw mode (red LED blinking). Maybe I missed that in the readme. Thanks!
