### ISSUE TITLE
Support for Raspberry pi 4

### ISSUE THREAD

**Issue by watanen1** [pakastin/homebridge-ruuvitag#5]
Should this work directly with Rasp4? I am getting weird error with Ruuvitag-debug installation:
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:138: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/usr/lib/node_modules/ruuvitag-debug/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ruuvitag-debug/node_modules/usb
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 (node_modules/ruuvitag-debug/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

This happens with homebridge-ruuvitag and ruuvitag-debug. I can see the plugin in homebridge but no accessories. With Bluetooth scanner I can find the ids and raspberry itself discovers the beacons...

**Comment by pakastin** [comment]
Should yeah, try install libudev:

```
sudo apt-get install -y libudev-dev
```

**Comment by watanen1** [comment]
That helped to get the accessories to homebridge (with reinstalling homebridge-ruuvitag and ruuvitag-debug). I can see values with ruuvitag-debug, but in homebridge the values for humidity and temperature are 0

**Comment by pakastin** [comment]
Have you tried switching Ruuvi to RAW mode?
https://lab.ruuvi.com/ruuvitag-fw/

**Comment by pakastin** [comment]
Should work with latest Raspberry Pi, probably user error so closing.

**Comment by tomppakoo** [comment]
Better late than never....but...
Try installing:
sudo npm install homebridge-ruuvitag -g --unsafe-perm

If you get zero values after install then:
sudo setcap cap_net_raw+eip $(eval readlink -f /usr/bin/node)

Hope this helps.

**Comment by vponnusamy** [comment]
> Better late than never....but...
> Try installing:
> sudo npm install homebridge-ruuvitag -g --unsafe-perm
> 
> If you get zero values after install then:
> sudo setcap cap_net_raw+eip $(eval readlink -f /usr/bin/node)
> 
> Hope this helps.

I was banging my head and this tip sorted me all out: `sudo npm install homebridge-ruuvitag -g --unsafe-perm`.  Thanks @tomppakoo !
