### ISSUE TITLE
needs root to work?

### ISSUE THREAD

**Issue by aqunt** [pakastin/homebridge-ruuvitag#8]
Hi,
I have issues getting values from ruuvitags to homekit. All tags report "0 C and 0% humidity". I noticed that using "ruuvitag-debug" nothing is printed but when I use "sudo ruuvitag-debug" I do get the data every second printed to screen. Phone ruuvi station reports correct values. I added homebridge user to bluetooth group and now bluetoothctl allows me to scan devices but still ruuvitag-debug / ruuvitag-homebridge gives me nothing. I'm using RaspberryPI4 (debian 10.4) with inbuilt usb chip with bluez 5.50 version.
Any suggestions where to look for the issues?

**Comment by pakastin** [comment]
Hi! Try these instructions:
https://github.com/abandonware/noble#running-without-rootsudo-linux-specific

Let me know if not working..

**Comment by aqunt** [comment]
Thanks. fixed it!

**Comment by pakastin** [comment]
Perfect! 👌
